### PR TITLE
Disabling bounce effect on every div

### PR DESCRIPTION
**Pull request by glemiere**
Fix for https://github.com/ionic-team/ionic/issues/11844#issuecomment-392202815
Fix originally proposed by @daansystems

### CODE REVIEW

**Comment by mlynch** [comment]
Thanks but this isn’t a solution to that problem and removing bouncing is not something we want. See my comment in that other issue for the rea problem and a possible solution

**Comment by glemiere** [comment]
Oh yeah you're right, I didn't think this through. Okay I'll finish my project and then look for the right condition to add. I guess detecting if the DisallowOverscroll parameter is set to true would be better, right ?

**Comment by floxcristian** [comment]
this solution did not work for me. :(

**Comment by glemiere** [comment]
@cristianfloresee 
Did you make sure the file was not getting overwritten ?
Did you modify the file in the `plugin` folder or in the `platforms/ios` folder ?

I'm pretty sure the solution is the answer to one of these questions ;-)

**Pull request closed without merging**
