### PR TITLE
Keyboard fixes for WK

### PR DESCRIPTION
**Pull request by manucorporat**

### CODE REVIEW

**Comment by mnewmedia** [comment]
Just tested for some days, feels soooo much better =) 
any reason you are waiting with merging?

**Comment by manucorporat** [comment]
@mnewmedia stay tuned! this will never be merged but we will release the new keyboard architecture soon!

**Comment by rohitgabriel** [comment]
Hi,
Any ETA on the new keyboard release date? Chatting on ionic feels a bit horrible

**Comment by tobiasmuecksch** [comment]
@manucorporat 
Any ETA on the new keyboard release date?

**Comment by kitkimwong** [comment]
Waiting for the new keyboard release!!!

**Comment by polfernandez** [comment]
With the branch ngx-translate for IOS devices does not work properly. 
Strings are not loaded, app shows the keys. WIth the native branch: [](https://github.com/ionic-team/cordova-plugin-ionic-webview)
translation work as expected, however the UI screen on Keyboard show moves the entire screen up even the top bar.

**Pull request closed without merging**
